sudo: false

matrix:
  include:
    - os: linux
      env: TARGET=x86_64-unknown-linux-musl

addons:
  apt:
    packages:
      - libpci-dev
      - libusb-dev
      - libusb-1.0-0-dev

script:
  - ./build.sh
